### ISSUE TITLE
Should we just use -csv with result summarizer?

### ISSUE THREAD

**Issue by emizan76** [mlcommons/logging#141]
After https://github.com/mlcommons/logging/pull/127, we MUST use -csv. Is that the assumption? Or shall I fix that and allow this to run w/o csv file?

emizan@emizan2:~/emizan_logging$ python3 -m mlperf_logging.result_summarizer ~/submission_training_1.0/Google/ training 1.0.0
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/google/home/emizan/emizan_logging/mlperf_logging/result_summarizer/__main__.py", line 3, in <module>
    result_summarizer.main()
  File "/usr/local/google/home/emizan/emizan_logging/mlperf_logging/result_summarizer/result_summarizer.py", line 376, in main
    summarize_results(args.folder, args.ruleset, csv_file)
UnboundLocalError: local variable 'csv_file' referenced before assignment

**Comment by emizan76** [comment]
https://github.com/mlcommons/logging/pull/144
