### ISSUE TITLE
[HPC-1.0.0 | compliance checker] Error for open division results

### ISSUE THREAD

**Issue by koichishirahata** [mlcommons/logging#172]
@sparticlesteve @azrael417 
Compliance checker shows FileNotFoundError for open division results. This error disappears by adding `open_common.yaml`. 

```
$ python3 -m mlperf_logging.package_checker $1 hpc 1.0.0
...
Run 1
Traceback (most recent call last):
  File "/home/shirahata/miniconda3/envs/pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/shirahata/miniconda3/envs/pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shirahata/mlperf-logging/mlperf_logging/package_checker/__main__.py", line 3, in <module>
    package_checker.main()
  File "/home/shirahata/mlperf-logging/mlperf_logging/package_checker/package_checker.py", line 269, in main
    check_training_package(args.folder, args.usage, args.ruleset, args.quiet, args.werror, args.rcp_bypass, args.rcp_bert_train_samples)
  File "/home/shirahata/mlperf-logging/mlperf_logging/package_checker/package_checker.py", line 213, in check_training_package
    check_training_result_files(folder, usage, ruleset, quiet, werror, rcp_bypass, rcp_bert_train_samples)
  File "/home/shirahata/mlperf-logging/mlperf_logging/package_checker/package_checker.py", line 145, in check_training_result_files
    checker,
  File "/home/shirahata/mlperf-logging/mlperf_logging/compliance_checker/mlp_compliance.py", line 326, in main
    valid = checker.check_file(filename, config_file)
  File "/home/shirahata/mlperf-logging/mlperf_logging/compliance_checker/mlp_compliance.py", line 277, in check_file
    self.check_loglines(loglines, config_file)
  File "/home/shirahata/mlperf-logging/mlperf_logging/compliance_checker/mlp_compliance.py", line 262, in check_loglines
    self.configured_checks(loglines,  config_file)
  File "/home/shirahata/mlperf-logging/mlperf_logging/compliance_checker/mlp_compliance.py", line 151, in configured_checks
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shirahata/mlperf-logging/mlperf_logging/compliance_checker/hpc_1.0.0/open_common.yaml'
```

**Comment by sparticlesteve** [comment]
Ah, thanks, @koichishirahata . This is an easy fix. We'll add an `open_common.yaml` ASAP.

**Comment by azrael417** [comment]
Adressed in https://github.com/mlcommons/logging/pull/176
